<div>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('login', array('controller' => 'management', 'action' => 'login')));
$form->prepare();
?>

    <div class="form‐group">
        <?php echo $this->form()->openTag($form); ?>
    </div>
    <div class="form‐group">
        <?php echo $this->formRow($form->get('username')); ?>
    </div>
    <div class="form‐group">
        <?php echo $this->formRow($form->get('password')); ?>
    </div>
    <div class="form‐group">
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>
    <div class="form‐group">
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>
