<?php //menu.phtml
    $currentYearEscaped = $this->escapeHtml($this->currentYear);
?>
<nav class="navbar opacity2" role="navigation">
    <ul class="nav navbar-nav">
        <li class="active"><a href="index/<?php echo $currentYearEscaped; ?>">Home</a></li>
        <li class="active"><a href="event/<?php echo $currentYearEscaped; ?>">Events</a></li>
        <li class="active"><a href="association/<?php echo $currentYearEscaped; ?>">Verein</a></li>
        <li class="active"><a href="gallery/<?php echo $currentYearEscaped; ?>">Gallerie</a></li>
    </ul>
    <div id="menu">
        <div class="topmenu">
            <a id="yearBtn" href=""><?php echo $this->currentYear; ?></a>
            <ul id="yearList">
                <?php foreach ($this->years as $year) : ?>
                    <li class="submenu<?php echo ($year == $this->currentYear ? ' selectedYear rounded' : '') ?>"><a href="<?php echo $this->escapeHtml($year); ?>"><?php echo $this->escapeHtml($year); ?></a></li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</nav>
