<?php //menu.phtml
    $currentYearEscaped = $this->escapeHtml($this->currentYear);
?>
<nav class="navbar opacity2" role="navigation">
    <ul class="nav navbar-nav">
        <li class="active"><a href="<?php echo $this->url('index', array('action'=>'index', 'year' => $this->currentYear));?>">Home</a></li>
        <li class="active"><a href="<?php echo $this->url('events', array('action'=>'index', 'year' => $this->currentYear));?>">Events</a></li>
        <li class="active"><a href="<?php echo $this->url('association', array('action'=>'index', 'year' => $this->currentYear));?>">Verein</a></li>
    </ul>
    <ul id="yearSelection" class="nav navbar-nav">
        <li class="nav navbar-nav dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <?php echo $this->currentYear; ?>
                <span class="caret"></span>
            </a>
            <ul class="dropdown-menu yearSelection_dropdown-menu">
                <?php foreach ($this->years as $year) : ?>
                    <li class="<?php echo ($year == $this->currentYear ? ' selectedYear' : '')?>">
                        <a href="<?php echo $this->url( $this->currentController, array('action'=>$this->currentAction, 'year'=>$year)); ?>"><?php echo $this->escapeHtml($year); ?></a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </li>
    </ul>
</nav>

<?php
if ($user = $this->identity()) {
?>
<nav class="navbar admin_navbar">

    <ul class="nav navbar-nav admin_navbar-nav">
        <li class="active">
            <a href="<?php echo $this->url($this->currentController, array('action'=>'manage', 'year' => $this->currentYear));?>">Bearbeiten</a>
        </li>
        <?php foreach($this->extraAdminActions as $action=>$title) { ?>
        <li class="active">
            <a href="<?php echo $this->url($this->currentController,array('action'=>$action, 'year' => $this->currentYear)); ?>"><?php echo($title); ?></a>
        </li>
        <?php } ?>
    </ul>
    <ul id="logout" class="nav navbar-nav admin_navbar-nav">
        <li class="active">
            <a href="<?php echo $this->url('admin',array('action'=>'logout')); ?>">Logout <?php echo $this->escapeHtml($user->getUsrName()); ?></a>
        </li>
    </ul>
</nav>
<?php
}
?>
