<?php
// Partial view of entity event
// 
// Arguments :
// addForm     Zend Form       AddMemberForm

$memberPhoto = $addForm->get('memberPhoto');

if($editMode) {
?>
<div class="clearfix"></div>
<?php } ?>
<div class="member col-md-12"  data-id="<?php echo $id ?>">
    <?php
    $addForm->setAttribute('data-id', $id);
    $addForm->prepare();
    echo $this->form()->openTag($addForm);
    ?>
    <div class="member rounded opacity2">
        <div class="row" >
            <div class="image col-md-4">
                
                <div class="fileinput fileinput-new" data-provides="fileinput">
                    <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 150px; min-height: 100px;">
                        <img src="<?php echo $memberPhoto->getValue(); ?>" alt="member photo">
                    </div>
                    <div>
                        <?php echo $this->formElementErrors($memberPhoto); ?>
                        <span class="btn btn-default btn-file">
                            <span class="fileinput-new">Laden</span>
                            <span class="fileinput-exists">Laden</span>
                            <?php echo $this->formFile($memberPhoto); ?>
                        </span>
                    </div> 
                </div>
            
            </div>
            <div class="col-md-8">
                <h3><?php echo $this->formText($addForm->get('name')); ?><?php echo $this->formText($addForm->get('prename')); ?></h3>
                <p><?php echo $this->formText($addForm->get('responsabilities')); ?></p>
            </div>
        </div>
        
        <div class="col-md-12">
            <?php
            $saveButton = $addForm->get('saveButton');
            $appendButton = $addForm->get('appendButton');
            $saveButton->setAttribute('data-id', $id);
            $appendButton->setAttribute('data-id', $id);
            
            if($editMode)
                echo $this->formElement($saveButton);
            else
                echo $this->formElement($appendButton);
            ?>
        </div>
    </div>
    <?php echo $this->form()->closeTag(); ?>
<?php echo '</div>'; ?>
