<?php
// Partial view of entity event
// 
// Arguments :
// addForm     Zend Form       AddMemberForm
?>
<div class="member rounded opacity2">
    <?php
    $addForm->setAttribute('action', 'add');
    $addForm->prepare();
    echo $this->form()->openTag($addForm);
    ?>
	<div class="title col-md-12">
	</br>
		<form enctype="multipart/form-data" action="parse_file.php" method="post"> 
		<p> Photo : <input type="file" name="uploaded_file"> </p>
		</form>
	</div>
	<div class="name col-md-12">
		<div class="title col-md-6">
			<h2><?php echo $this->formText($addForm->get('name')); ?></h2>
		</div>
		<div class="title col-md-6">
			<h2><?php echo $this->formText($addForm->get('prename')); ?></h2>
		</div>
	</div>
    <div class="description col-md-10">
        <p><?php echo $this->formTextarea($addForm->get('responsabilities')); ?></p>
    </div>
    <div class="management-buttons col-md-2">
         <?php
        if($editMode)
            echo $this->formElement($addForm->get('saveButton'));
        else
            echo $this->formElement($addForm->get('postButton'));
        ?>
    </div>
    <div style="clear:both;"></div>
<?php if(!$editMode) {?>
</div>
<?php }?>