<?php
// Partial view of entity event
// 
// Arguments :
// addForm     Zend Form       AddMemberForm
?>

<div class="clearfix"></div>
<div class="col-md-12">
    <?php
    $addForm->prepare();
    ?>
    <div class="event rounded opacity2">
        <div class="row" >
            <div class="image col-md-3">
                Photo : <input type="file" name="uploaded_file" /> 
            </div>
            <div class="col-md-9">
                <h3><?php echo $this->formText($addForm->get('name')); ?><?php echo $this->formText($addForm->get('prename')); ?></h3>
                <p><?php echo $this->formText($addForm->get('responsabilities')); ?></p>
            </div>
        </div>
        
        <div class="col-md-12">
            <?php
            if($editMode)
                echo $this->formElement($addForm->get('saveButton'));
            else
                echo $this->formElement($addForm->get('postButton'));
            ?>
        </div>
    </div>
</div>
