<?php
// Partial view of entity event
// 
// Arguments :
// id           int             Id of member
// name         String          Member name
// prename      String          Member prename
// imagePath    String          Member image
// responsabilites ????        
// editMode     Boolean         Is the view use to edit
// editForm     Zend Form       Edit button form (only needed when editMode is true)
// deleteForm   Zend Form       Delete button form (only needed when editMode is true)
// Member       Member entity   Object to be shown

// Set german as main language


echo '<div class="member col-md-6" data-id="'.$id.'">'; ?>
    <div class="rounded opacity2">
        <div class="row" >
            <div class="image col-md-3">
                <img class="memberPhoto" src="<?php echo $imagePath ?>" alt="Photo">
            </div>
            <div class="col-md-9">
                <h3><?php echo utf8_encode($name . " " . $prename); ?></h3>
                <p><?php echo utf8_encode($responsabilites); ?></p>
            </div>
        </div>
        
        <?php if(isset($editMode) && $editMode){ ?>
        <div class="col-md-12">
            <button class="btn btn-sm editButton" data-id="<?php echo $id;?>">Edit</button>
            <button class="btn btn-sm deleteButton" data-id="<?php echo $id;?>">Delete</button>
        </div>
        <?php }?>
    </div>
<?php echo '</div>';?>
