<?php
// Partial view of entity event
// 
// Arguments :
// Event    Event entity    Object to be shown
// Manager  Boolean         Is the view use to edit
?>
<div class="event rounded opacity2">
    <div class="col-md-3">
        <div class="heading">
            <div class="date">
                <div class="weekday text-center"><?php echo date('l',$date->getTimestamp()); ?></div>
                <div class="day text-center"><?php echo date('j. F',$date->getTimestamp()); ?></div>
            </div>
            <div class="time">
                <div class="hour text-center"><?php //echo $startHour; ?></div>
                <div class="hour text-center"><?php //$endHour; ?></div>
            </div>
        </div>
    </div>
    <h2 class="title col-md-9"><?php echo $title; ?></h2>
    <p class="description col-md-12"><?php echo $content; ?></p>
</div>