<?php
// Partial view of entity event
// 
// Arguments :
// date         Php DateTime    Date when the event is occuring
// id           int             Id of event
// startHour    Php DateTime    Start time of event
// endHour      Php DateTime    End time of event
// title        String          Event title
// content      String          Event description
// editMode     Boolean         Is the view use to edit
// addForm      Zend Form       AddEventForm
?>
<?php if(!$editMode) {?>
<div class="event rounded opacity2">
<?php }?>
    <?php
    $addForm->prepare();
    ?>
    <div class="col-md-4 colorBackground">
        <div id="append" class="heading">
            <div class="date">
                <div class="weekday text-center"><?php echo $this->formSelect($addForm->get('day')); ?></div>
                <div class="day text-center"><?php echo $this->formSelect($addForm->get('month')); ?></div>
            </div>
            <div class="time">
                <div class="hour text-center"><?php echo $this->formSelect($addForm->get('start_time')); ?></div>
                <div class="hour text-center"><?php echo $this->formSelect($addForm->get('stop_time')); ?></div>
            </div>
        </div>
    </div>
    <div class="title col-md-8">
        <h2><?php echo $this->formText($addForm->get('title')); ?></h2>
    </div>
    <div class="description col-md-10">
        <p><?php echo $this->formTextarea($addForm->get('description')); ?></p>
    </div>
    <div class="management-buttons col-md-2">
        <?php
        if($editMode)
            echo $this->formElement($addForm->get('saveButton'));
        else
            echo $this->formElement($addForm->get('postButton'));
        ?>
    </div>
    <div style="clear:both;"></div>
<?php if(!$editMode) {?>
</div>
<?php }?>