<?php
// Partial view of entity event
// 
// Arguments :
// Event    Event entity    Object to be shown
// Manager  Boolean         Is the view use to edit
?>
<div class="event rounded opacity2">
    <div class="col-md-3">
        <div class="heading">
            <div class="date">
                <div class="weekday text-center">Freitag</div>
                <div class="day text-center">20. Sept</div>
            </div>
            <div class="time">
                <div class="hour text-center">14:30</div>
                <div class="hour text-center">16:30</div>
            </div>
        </div>
    </div>
    <h2 class="title col-md-9"><?php echo $this->event->getTitle();?></h2>
    <p class="description col-md-12">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet qis luctus, metus</p>
</div>