<?php
echo $this->partial('partial/menu', $menuParams);
echo '<div id="posting_errors"></div>';
// Receiving event list and parsing
echo '<div class="eventsContainer" id="allEvents">';
foreach($eventList as $event)
{
    echo $this->partial('application/events/partial/event.phtml', array(
        'date' => $event->getDate(),
        'id' => $event->getId(),
        'startHour' => $event->getStartTime(),
        'endHour' => $event->getEndTime(),
        'title' => $event->getTitle(),
        'content' => $event->getDescription(),
        'editMode' => true,));
}
echo '</div>';

echo $this->partial('application/events/partial/event_form.phtml', array('addForm' => $addForm,
                                                                        'editMode' => false)); ?>
<script type="text/javascript">
    function show_fill_error() {
        document.getElementById('posting_errors').innerHTML = '<div class="alert alert-danger"><a class="close" data-dismiss="alert">&times;</a>Please fill all fields</div>';
    }
$(".postButton").click(function() {
        var title = $('input#title').val();
        var description = $('textarea#description').val();
        var day = $('#days').val();
        var month = $('#month').val();
        var start_time = $('#start_time').val();
        var stop_time = $('#stop_time').val();
        
        if(description == '' || title == '') {
            show_fill_error();
        }else{
            $.ajax({
                url: 'add',
                type: 'POST',
                dataType: 'html',
                data: {
                    title: title,
                    description: description,
                    day: day,
                    month: month,
                    start_time: start_time,
                    stop_time: stop_time,
                },
                success: function(html) {
                    document.getElementById('allEvents').innerHTML += html;
                }
            });
        }
    });
    
    $(document).delegate('.editButton', 'click', function() {
        var id = $(this).attr('data-id');
        
            $.ajax({
                url: 'geteditform/'+id,
                type: 'POST',
                dataType: 'html',
                data: {},
                success: function(html) {
                    document.getElementById('allEvents').innerHTML = document.getElementById('allEvents').innerHTML.replace(document.getElementById('event-'+id).innerHTML,html);
                }
            });
        
    });
    
    $(document).delegate('.saveButton', 'click', function() {
        var id = $(this).attr('data-id');
        
        var title = $('input#title-'+id).val();
        var description = $('textarea#description-'+id).val();
        var day = $('#days-'+id).val();
        var month = $('#month-'+id).val();
        var start_time = $('#start_time-'+id).val();
        var stop_time = $('#stop_time-'+id).val();
        
        if(description == '' || title == '') {
            show_fill_error();
        }else{
            $.ajax({
                url: 'edit/'+id,
                type: 'POST',
                dataType: 'html',
                data: {
                    title: title,
                    description: description,
                    day: day,
                    month: month,
                    start_time: start_time,
                    stop_time: stop_time,
                },
                success: function(html) {
                    document.getElementById('allEvents').innerHTML = document.getElementById('allEvents').innerHTML.replace(document.getElementById('event-'+id).innerHTML,html);
                }
            });
        }
    });
    
    $(".deleteButton").click(function() {
        var id = $(this).attr('data-id');
        
        // Remove from page
        var div = document.getElementById('event-'+id);
        div.parentNode.removeChild(div);
        
        // TODO Verification
            $.ajax({
                url: 'delete/'+id,
                type: 'POST',
                dataType: 'JSON',
                data: {},
                success: function(json) {
                }
            });
        
    });
    </script>