<?php
echo $this->partial('partial/menu', $menuParams);

// Receiving event list and parsing
foreach($eventList as $event)
{
    echo $this->partial('application/events/partial/event.phtml', array(
        'date' => $event->getDate(),
        'id' => $event->getId(),
        'startHour' => $event->getStartTime(),
        'endHour' => $event->getEndTime(),
        'title' => $event->getTitle(),
        'content' => $event->getDescription(),
        'editMode' => true,
        'editForm' => $editForm,
        'deleteForm' => $deleteForm,));
}

echo $this->partial('application/events/partial/event_form.phtml', array('addForm' => $addForm,));