<?php
echo $this->partial('partial/menu', $menuParams);

?>

<div class="row">
<?php
// Receiving event list and parsing
foreach($carnivalYear->getMembers() as $member)
{
    echo ($this->partial(
        'application/association/partial/member.phtml',
        array(
            'id' => $member->getId(),
            'prename' => $member->getPrename(),
            'name' => $member->getName(),
            'imagePath' => $imagePath.$member->getImagePath(),
            'responsabilites' => $member->getResponsabilites(),
        )
    ));
}

?>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="staticInfo rounded opacity2">
            <h2>Vereinsgeschichte</h2>
            <div>
                <?php echo( $association ); ?>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="staticInfo rounded opacity2">
            <h2>Mitglied werden</h2>
            <div>
                <?php echo( $joinus ); ?>
            </div>
        </div>
    </div>
</div>
