<?php
echo $this->partial('partial/menu', $menuParams);

?>

<div class="row">
<?php
// Receiving event list and parsing
foreach($carnivalYear->getOrganisators() as $organisator)
{
    $member = $organisator->getMember();
    echo($this->partial(
        'application/association/partial/member.phtml',
        array(
            'id' => $member->getId(),
            'prename' => $member->getPrename(),
            'name' => $member->getName(),
            'imagePath' => $imagePath.$member->getImagePath(),
            'responsabilites' => $organisator->getResponsabilites(),
        )
    ));
}

?>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="event rounded opacity2">
            <h2>Vereinsgeschichte</h2>
            <p>
                <?php echo( $association ); ?>
            </p>
        </div>
    </div>
    <div class="col-md-12">
        <div class="event rounded opacity2">
            <h2>Mitglied werden</h2>
            <p>
                <?php echo( $joinus ); ?>
            </p>
        </div>
    </div>
</div>
