<?php
echo $this->partial('partial/menu', $menuParams);

// Receiving event list and parsing
foreach($organisatorList as $organisator)
{
	$member = $organisator->getMember();
    echo $this->partial('application/association/partial/member.phtml', array(
        'id' => $member->getId(),
        'prename' => $member->getPrename(),
        'name' => $member->getName(),
        'imagePath' => $imagePath.$member->getImagePath(),
		'responsabilites' =>$organisator->getResponsabilites(),
        'editMode' => true,
        'editForm' => $editForm,
        'deleteForm' => $deleteForm,));
}

echo $this->partial('application/association/partial/member_form.phtml', array('addForm' => $addForm,));