<?php
echo $this->partial('partial/menu', $menuParams);

echo '<div id="posting_errors"></div>';

// Receiving member list and parsing
?>
<div class="row" id="allMembers">
<?php foreach($carnivalYear->getOrganisators() as $organisator)
{
    $member = $organisator->getMember();
    echo $this->partial('application/association/partial/member.phtml', array(
        'id' => $member->getId(),
        'prename' => $member->getPrename(),
        'name' => $member->getName(),
        'imagePath' => $imagePath.$member->getImagePath(),
        'responsabilites' =>$organisator->getResponsabilites(),
        'editMode' => true,));
}
?>
<?php echo $this->partial('application/association/partial/member_form.phtml', array('addForm' => $addForm,
                                                                        'editMode' => false)); ?>
</div>

<script type="text/javascript">
    function show_fill_error() {
        document.getElementById('posting_errors').innerHTML = '<div class="alert alert-danger"><a class="close" data-dismiss="alert">&times;</a>Please fill all fields</div>';
    }
    
    $(document).delegate('.postButton', 'click',function() {
        
        var imagePath = $('input#imagePath').val();
        var name = $('input#name').val();
        var prename = $('input#prename').val();
        var responsabilities = $('input#responsabilities').val();
        
        if(name == '' || prename == '') {
            show_fill_error();
        }else{
            $.ajax({
                url: '<?php echo $base_url;?>add/<?php echo $carnivalYear->getYear(); ?>',
                type: 'POST',
                dataType: 'html',
                data: {
                    imagePath: imagePath,
                    name: name,
                    prename: prename,
                    responsabilities: responsabilities,
                },
                success: function(html) {
                    document.getElementById('allMembers').innerHTML += html;
                }
            });
        }
    });
    
    $(document).delegate('.editButton', 'click', function() {
        var id = $(this).attr('data-id');
        
            $.ajax({
                url: '<?php echo $base_url;?>geteditform/'+id,
                type: 'POST',
                dataType: 'html',
                data: {},
                success: function(html) {
                   document.getElementById('member-'+id).innerHTML = html;
                }
            });
        
    });
    
    $(document).delegate('.saveButton', 'click', function() {
        var id = $(this).attr('data-id');
        
        
        var imagePath = $('input#imagePath-'+id).val();
        var name = $('input#name-'+id).val();
        var prename = $('input#prename-'+id).val();
        var responsabilities = $('input#responsabilities-'+id).val();
        
        if(name == '' || prename == '') {
            show_fill_error();
        }else{
            $.ajax({
                url: '<?php echo $base_url;?>edit/'+id,
                type: 'POST',
                dataType: 'html',
                data: {
                    imagePath: imagePath,
                    name: name,
                    prename: prename,
                    responsabilities: responsabilities,
                },
                success: function(html) {
                   document.getElementById('member-'+id).innerHTML = html;
                }
            });
        }
    });
    
    $(document).delegate('.deleteButton', 'click', function() {
        if(confirm("Delete this member ?"))
        {
            var id = $(this).attr('data-id');

            // Remove from page
            var div = document.getElementById('member-'+id);
            div.parentNode.removeChild(div);

            // TODO Verification
            $.ajax({
                url: '<?php echo $base_url;?>delete/'+id,
                type: 'POST',
                dataType: 'JSON',
                data: {},
                success: function(json) {
                }
            });
        }
    });
    </script>
